name: gailwhipple
favicon: null
layout_spectrum: 0.8786980444565415
typography_spectrum: 0.5715747619979084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4288643419276923
  lightness: 0.7825731583870947
  saturation: 0.879679542966187
  rhythmicContrast: 0.4132980112917721
purpose: []
